import type { Lead } from "@/types/lead"

export const mockLeads: Lead[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.johnson@techcorp.com",
    status: "New",
    createdAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "2",
    name: "Michael Chen",
    email: "m.chen@innovatetech.io",
    status: "Engaged",
    createdAt: "2024-01-14T14:22:00Z",
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    email: "emily.r@digitalstudio.com",
    status: "Proposal Sent",
    createdAt: "2024-01-13T09:15:00Z",
  },
  {
    id: "4",
    name: "David Thompson",
    email: "david.thompson@startupventures.com",
    status: "Closed-Won",
    createdAt: "2024-01-12T16:45:00Z",
  },
  {
    id: "5",
    name: "Lisa Wang",
    email: "lisa.wang@cloudservices.net",
    status: "Closed-Lost",
    createdAt: "2024-01-11T11:20:00Z",
  },
  {
    id: "6",
    name: "Robert Martinez",
    email: "r.martinez@ecommercepro.com",
    status: "New",
    createdAt: "2024-01-10T13:30:00Z",
  },
  {
    id: "7",
    name: "Jennifer Kim",
    email: "jennifer.kim@healthtech.org",
    status: "Engaged",
    createdAt: "2024-01-09T08:45:00Z",
  },
  {
    id: "8",
    name: "Alex Turner",
    email: "alex.turner@financeapp.co",
    status: "Proposal Sent",
    createdAt: "2024-01-08T15:10:00Z",
  },
  {
    id: "9",
    name: "Maria Gonzalez",
    email: "maria.g@retailsolutions.com",
    status: "Closed-Won",
    createdAt: "2024-01-07T12:00:00Z",
  },
  {
    id: "10",
    name: "James Wilson",
    email: "james.wilson@logisticsplus.net",
    status: "New",
    createdAt: "2024-01-06T10:15:00Z",
  },
  {
    id: "11",
    name: "Amanda Foster",
    email: "amanda.foster@marketinggenius.com",
    status: "Engaged",
    createdAt: "2024-01-05T14:30:00Z",
  },
  {
    id: "12",
    name: "Kevin Lee",
    email: "kevin.lee@cybersecurity.pro",
    status: "Closed-Lost",
    createdAt: "2024-01-04T09:20:00Z",
  },
  {
    id: "13",
    name: "Rachel Brown",
    email: "rachel.brown@edtech.edu",
    status: "New",
    createdAt: "2024-01-03T16:40:00Z",
  },
  {
    id: "14",
    name: "Daniel Park",
    email: "daniel.park@gamedev.studio",
    status: "Proposal Sent",
    createdAt: "2024-01-02T11:55:00Z",
  },
  {
    id: "15",
    name: "Sophie Miller",
    email: "sophie.miller@fashiontech.com",
    status: "Engaged",
    createdAt: "2024-01-01T13:25:00Z",
  },
  {
    id: "16",
    name: "Thomas Anderson",
    email: "thomas.anderson@airesearch.org",
    status: "Closed-Won",
    createdAt: "2023-12-31T15:45:00Z",
  },
  {
    id: "17",
    name: "Olivia Davis",
    email: "olivia.davis@greentech.eco",
    status: "New",
    createdAt: "2023-12-30T08:30:00Z",
  },
  {
    id: "18",
    name: "Christopher Taylor",
    email: "chris.taylor@sportsmedia.tv",
    status: "Engaged",
    createdAt: "2023-12-29T12:15:00Z",
  },
  {
    id: "19",
    name: "Isabella Garcia",
    email: "isabella.garcia@fooddelivery.app",
    status: "Closed-Lost",
    createdAt: "2023-12-28T14:50:00Z",
  },
  {
    id: "20",
    name: "Matthew White",
    email: "matthew.white@traveltech.com",
    status: "Proposal Sent",
    createdAt: "2023-12-27T10:05:00Z",
  },
  {
    id: "21",
    name: "Grace Liu",
    email: "grace.liu@biotech.research",
    status: "New",
    createdAt: "2023-12-26T16:20:00Z",
  },
  {
    id: "22",
    name: "Andrew Jackson",
    email: "andrew.jackson@proptech.real",
    status: "Closed-Won",
    createdAt: "2023-12-25T09:40:00Z",
  },
  {
    id: "23",
    name: "Natalie Cooper",
    email: "natalie.cooper@musicstreaming.fm",
    status: "Engaged",
    createdAt: "2023-12-24T13:10:00Z",
  },
  {
    id: "24",
    name: "Ryan Murphy",
    email: "ryan.murphy@autotech.drive",
    status: "Proposal Sent",
    createdAt: "2023-12-23T11:35:00Z",
  },
]
